runtime: nodejs16

env_variables:
  EWELINK_EMAIL: <<ewelink_email>>
  EWELINK_PASSWORD: <<ewelink_password>>
  PASSWORD: <<password>>
  PUBLIC_URL: https://quickstart-1561997957317.ew.r.appspot.com

automatic_scaling:
  max_instances: 1